apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  namespace: solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: karamfci/mh-repo:30
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
